syntax = "proto3";

option go_package = "github.com/knusbaum/kitsync/ksrpc";
package ksrpc;

// The greeting service definition.
service Controller {
  rpc Sync (Void) returns (Void) {}
  rpc Reindex (Void) returns (Void) {}
  rpc Put(stream ContentChunk) returns (AddReply) {}
  rpc Delete(ID) returns (Void) {}
  rpc Lookup(ID) returns (LookupResult) {}
  rpc Iter(Void) returns (stream ID) {}

  // Index functions
  rpc Search(Query) returns (stream ID) {}
  rpc Keys(Void) returns (stream Str) {}
  rpc Tags(Void) returns (stream Str) {}

  // Object functions
  rpc AddTags(ObjectRequest) returns (Void) {}
  rpc DelTags(ObjectRequest) returns (Void) {}
  rpc Content(ObjectRequest) returns (stream ContentChunk) {}
}

message Void {}

// The request message containing the user's name.
message ContentChunk {
	map<string, string> Tags = 1;
	bytes Data = 2;
}

message AddReply {
	string ID = 1;
}

message Query {
	string Key = 1;
	string Value = 2;
}

message ID {
	string ID = 1;
}

message LookupResult {
	map<string, string> Tags = 1;
	bool Present = 2;
}

message ObjectRequest {
	string ID = 1;
	map<string, string> Tags = 2;
}

message Str {
	string S = 1;
}