// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: kitsync.proto

package ksrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	// Sends a greeting
	Sync(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
	Add(ctx context.Context, opts ...grpc.CallOption) (Controller_AddClient, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Sync(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/ksrpc.Controller/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Add(ctx context.Context, opts ...grpc.CallOption) (Controller_AddClient, error) {
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[0], "/ksrpc.Controller/Add", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerAddClient{stream}
	return x, nil
}

type Controller_AddClient interface {
	Send(*ContentChunk) error
	CloseAndRecv() (*AddReply, error)
	grpc.ClientStream
}

type controllerAddClient struct {
	grpc.ClientStream
}

func (x *controllerAddClient) Send(m *ContentChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controllerAddClient) CloseAndRecv() (*AddReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility
type ControllerServer interface {
	// Sends a greeting
	Sync(context.Context, *Void) (*Void, error)
	Add(Controller_AddServer) error
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (UnimplementedControllerServer) Sync(context.Context, *Void) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedControllerServer) Add(Controller_AddServer) error {
	return status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ksrpc.Controller/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Sync(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Add_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServer).Add(&controllerAddServer{stream})
}

type Controller_AddServer interface {
	SendAndClose(*AddReply) error
	Recv() (*ContentChunk, error)
	grpc.ServerStream
}

type controllerAddServer struct {
	grpc.ServerStream
}

func (x *controllerAddServer) SendAndClose(m *AddReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controllerAddServer) Recv() (*ContentChunk, error) {
	m := new(ContentChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ksrpc.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Controller_Sync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Add",
			Handler:       _Controller_Add_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "kitsync.proto",
}
