// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: kitsync.proto

package ksrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	Sync(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
	Reindex(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error)
	Put(ctx context.Context, opts ...grpc.CallOption) (Controller_PutClient, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Void, error)
	Lookup(ctx context.Context, in *ID, opts ...grpc.CallOption) (*LookupResult, error)
	Iter(ctx context.Context, in *Void, opts ...grpc.CallOption) (Controller_IterClient, error)
	// Index functions
	Search(ctx context.Context, in *Query, opts ...grpc.CallOption) (Controller_SearchClient, error)
	Keys(ctx context.Context, in *Void, opts ...grpc.CallOption) (Controller_KeysClient, error)
	Tags(ctx context.Context, in *Void, opts ...grpc.CallOption) (Controller_TagsClient, error)
	// Object functions
	AddTags(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*Void, error)
	DelTags(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*Void, error)
	Content(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (Controller_ContentClient, error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Sync(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/ksrpc.Controller/Sync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Reindex(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/ksrpc.Controller/Reindex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Put(ctx context.Context, opts ...grpc.CallOption) (Controller_PutClient, error) {
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[0], "/ksrpc.Controller/Put", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerPutClient{stream}
	return x, nil
}

type Controller_PutClient interface {
	Send(*ContentChunk) error
	CloseAndRecv() (*AddReply, error)
	grpc.ClientStream
}

type controllerPutClient struct {
	grpc.ClientStream
}

func (x *controllerPutClient) Send(m *ContentChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *controllerPutClient) CloseAndRecv() (*AddReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AddReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/ksrpc.Controller/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Lookup(ctx context.Context, in *ID, opts ...grpc.CallOption) (*LookupResult, error) {
	out := new(LookupResult)
	err := c.cc.Invoke(ctx, "/ksrpc.Controller/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Iter(ctx context.Context, in *Void, opts ...grpc.CallOption) (Controller_IterClient, error) {
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[1], "/ksrpc.Controller/Iter", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerIterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_IterClient interface {
	Recv() (*ID, error)
	grpc.ClientStream
}

type controllerIterClient struct {
	grpc.ClientStream
}

func (x *controllerIterClient) Recv() (*ID, error) {
	m := new(ID)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) Search(ctx context.Context, in *Query, opts ...grpc.CallOption) (Controller_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[2], "/ksrpc.Controller/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_SearchClient interface {
	Recv() (*ID, error)
	grpc.ClientStream
}

type controllerSearchClient struct {
	grpc.ClientStream
}

func (x *controllerSearchClient) Recv() (*ID, error) {
	m := new(ID)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) Keys(ctx context.Context, in *Void, opts ...grpc.CallOption) (Controller_KeysClient, error) {
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[3], "/ksrpc.Controller/Keys", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerKeysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_KeysClient interface {
	Recv() (*Str, error)
	grpc.ClientStream
}

type controllerKeysClient struct {
	grpc.ClientStream
}

func (x *controllerKeysClient) Recv() (*Str, error) {
	m := new(Str)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) Tags(ctx context.Context, in *Void, opts ...grpc.CallOption) (Controller_TagsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[4], "/ksrpc.Controller/Tags", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerTagsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_TagsClient interface {
	Recv() (*Str, error)
	grpc.ClientStream
}

type controllerTagsClient struct {
	grpc.ClientStream
}

func (x *controllerTagsClient) Recv() (*Str, error) {
	m := new(Str)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controllerClient) AddTags(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/ksrpc.Controller/AddTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) DelTags(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/ksrpc.Controller/DelTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Content(ctx context.Context, in *ObjectRequest, opts ...grpc.CallOption) (Controller_ContentClient, error) {
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[5], "/ksrpc.Controller/Content", opts...)
	if err != nil {
		return nil, err
	}
	x := &controllerContentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Controller_ContentClient interface {
	Recv() (*ContentChunk, error)
	grpc.ClientStream
}

type controllerContentClient struct {
	grpc.ClientStream
}

func (x *controllerContentClient) Recv() (*ContentChunk, error) {
	m := new(ContentChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility
type ControllerServer interface {
	Sync(context.Context, *Void) (*Void, error)
	Reindex(context.Context, *Void) (*Void, error)
	Put(Controller_PutServer) error
	Delete(context.Context, *ID) (*Void, error)
	Lookup(context.Context, *ID) (*LookupResult, error)
	Iter(*Void, Controller_IterServer) error
	// Index functions
	Search(*Query, Controller_SearchServer) error
	Keys(*Void, Controller_KeysServer) error
	Tags(*Void, Controller_TagsServer) error
	// Object functions
	AddTags(context.Context, *ObjectRequest) (*Void, error)
	DelTags(context.Context, *ObjectRequest) (*Void, error)
	Content(*ObjectRequest, Controller_ContentServer) error
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have forward compatible implementations.
type UnimplementedControllerServer struct {
}

func (UnimplementedControllerServer) Sync(context.Context, *Void) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedControllerServer) Reindex(context.Context, *Void) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reindex not implemented")
}
func (UnimplementedControllerServer) Put(Controller_PutServer) error {
	return status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedControllerServer) Delete(context.Context, *ID) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedControllerServer) Lookup(context.Context, *ID) (*LookupResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedControllerServer) Iter(*Void, Controller_IterServer) error {
	return status.Errorf(codes.Unimplemented, "method Iter not implemented")
}
func (UnimplementedControllerServer) Search(*Query, Controller_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedControllerServer) Keys(*Void, Controller_KeysServer) error {
	return status.Errorf(codes.Unimplemented, "method Keys not implemented")
}
func (UnimplementedControllerServer) Tags(*Void, Controller_TagsServer) error {
	return status.Errorf(codes.Unimplemented, "method Tags not implemented")
}
func (UnimplementedControllerServer) AddTags(context.Context, *ObjectRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTags not implemented")
}
func (UnimplementedControllerServer) DelTags(context.Context, *ObjectRequest) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelTags not implemented")
}
func (UnimplementedControllerServer) Content(*ObjectRequest, Controller_ContentServer) error {
	return status.Errorf(codes.Unimplemented, "method Content not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ksrpc.Controller/Sync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Sync(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Reindex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Reindex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ksrpc.Controller/Reindex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Reindex(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServer).Put(&controllerPutServer{stream})
}

type Controller_PutServer interface {
	SendAndClose(*AddReply) error
	Recv() (*ContentChunk, error)
	grpc.ServerStream
}

type controllerPutServer struct {
	grpc.ServerStream
}

func (x *controllerPutServer) SendAndClose(m *AddReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *controllerPutServer) Recv() (*ContentChunk, error) {
	m := new(ContentChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Controller_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ksrpc.Controller/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ksrpc.Controller/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Lookup(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Iter_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).Iter(m, &controllerIterServer{stream})
}

type Controller_IterServer interface {
	Send(*ID) error
	grpc.ServerStream
}

type controllerIterServer struct {
	grpc.ServerStream
}

func (x *controllerIterServer) Send(m *ID) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Query)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).Search(m, &controllerSearchServer{stream})
}

type Controller_SearchServer interface {
	Send(*ID) error
	grpc.ServerStream
}

type controllerSearchServer struct {
	grpc.ServerStream
}

func (x *controllerSearchServer) Send(m *ID) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_Keys_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).Keys(m, &controllerKeysServer{stream})
}

type Controller_KeysServer interface {
	Send(*Str) error
	grpc.ServerStream
}

type controllerKeysServer struct {
	grpc.ServerStream
}

func (x *controllerKeysServer) Send(m *Str) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_Tags_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).Tags(m, &controllerTagsServer{stream})
}

type Controller_TagsServer interface {
	Send(*Str) error
	grpc.ServerStream
}

type controllerTagsServer struct {
	grpc.ServerStream
}

func (x *controllerTagsServer) Send(m *Str) error {
	return x.ServerStream.SendMsg(m)
}

func _Controller_AddTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).AddTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ksrpc.Controller/AddTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).AddTags(ctx, req.(*ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_DelTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).DelTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ksrpc.Controller/DelTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).DelTags(ctx, req.(*ObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Content_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).Content(m, &controllerContentServer{stream})
}

type Controller_ContentServer interface {
	Send(*ContentChunk) error
	grpc.ServerStream
}

type controllerContentServer struct {
	grpc.ServerStream
}

func (x *controllerContentServer) Send(m *ContentChunk) error {
	return x.ServerStream.SendMsg(m)
}

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ksrpc.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _Controller_Sync_Handler,
		},
		{
			MethodName: "Reindex",
			Handler:    _Controller_Reindex_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Controller_Delete_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _Controller_Lookup_Handler,
		},
		{
			MethodName: "AddTags",
			Handler:    _Controller_AddTags_Handler,
		},
		{
			MethodName: "DelTags",
			Handler:    _Controller_DelTags_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _Controller_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Iter",
			Handler:       _Controller_Iter_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Search",
			Handler:       _Controller_Search_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Keys",
			Handler:       _Controller_Keys_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Tags",
			Handler:       _Controller_Tags_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Content",
			Handler:       _Controller_Content_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "kitsync.proto",
}
